-- plugins
require("src.options")
require("src.keymaps")
require("src.plugins")
require("src.colorscheme")
require("src.comment")
require("src.telescope")
require("src.treesitter")
require("src.gitsigns")
require("src.nvim-tree")
require("src.bufferline")
require("src.lualine")
require("src.alpha")
require("src.whichkey")
require("src.icons")
require("src.custom-commands")
require("src.lsp")
